### ISSUE TITLE
Crash when compiling to run using gradlew.bat run

### ISSUE THREAD

**Issue by swimmerwoad** [demilich1/metastone#216]
java.lang.ClassNotFoundException: net.demilich.metastone.game.spells.custom.MindGamesSpell09:28:27 ERROR - Trouble reading spell_mindgames.json

        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at net.demilich.metastone.game.cards.desc.SpellDeserializer.deserialize(SpellDeserializer.java:28)
        at net.demilich.metastone.game.cards.desc.SpellDeserializer.deserialize(SpellDeserializer.java:16)
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
        at com.google.gson.Gson.fromJson(Gson.java:810)
        at com.google.gson.Gson.fromJson(Gson.java:875)
        at com.google.gson.Gson.fromJson(Gson.java:848)
        at net.demilich.metastone.game.cards.CardParser.parseCard(CardParser.java:74)
        at net.demilich.metastone.game.cards.CardCatalogue.loadCards(CardCatalogue.java:154)
        at net.demilich.metastone.game.cards.CardCatalogue.loadCards(CardCatalogue.java:145)
        at net.demilich.metastone.gui.cards.CardProxy.<init>(CardProxy.java:26)
        at net.demilich.metastone.ApplicationStartupCommand.execute(ApplicationStartupCommand.java:19)
        at net.demilich.nittygrittymvc.CommandObserverWrapper.handleNotification(CommandObserverWrapper.java:16)
        at net.demilich.nittygrittymvc.Facade.notifyObservers(Facade.java:79)
        at net.demilich.nittygrittymvc.Facade.sendNotification(Facade.java:177)
        at net.demilich.nittygrittymvc.Facade.sendNotification(Facade.java:166)
        at net.demilich.metastone.ApplicationFacade.startUp(ApplicationFacade.java:97)
        at net.demilich.metastone.MetaStone.start(MetaStone.java:45)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWaitatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonParseException: SpellDesc parser encountered an invalid spell class: net.demilich.metastone.game.spells.custom.MindGamesSpell
        at net.demilich.metastone.game.cards.desc.SpellDeserializer.deserialize(SpellDeserializer.java:31)
        at net.demilich.metaame.cards.desc.SpellDeserializer.deserialize(SpellDeserializer.java:16)
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
        at com.google.gson.Gson.fromJson(Gson.java:810)
        at com.google.gson.Gson.fromJson(Gson.java:875)
        at com.google.gson.Gson.fromJson(Gson.java:848)
        at net.demilich.metastone.game.cards.CardParser.parseCard(CardParser.java:74)
        at net.demilich.metastone.game.cards.CardCatalogue.loadCards(CardCatalogue.java:154)
        at net.demilich.metastone.game.cards.CardCatalogue.loadCards(CardCatalogue.java:145)
        at net.demilich.metastone.gui.cards.CardProxy.<init>(CardProxy.java:26)
        at net.demilich.metastone.ApplicationStartupCommand.execute(ApplicationStartupCommand.java:19)
        at net.demilich.nittygrittymvc.CommandObserverWrapper.handleNotification(CommandObserverWrapper.java:16)
        at net.demilich.nittygrittymvc.Facade.notifyObservers(Facade.java:79)
        at net.demilich.nittygrittymvc.Facade.sendNotification(Facade.java:177)
        at net.demilich.nittygrittymvc.Facade.sendNotification(Facade.java:166)
        at net.demilich.metastone.ApplicationFacade.startUp(ApplicationFacade.java:97)
        at net.demilich.metastone.MetaStone.start(MetaStone.java:45)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$14plication.java:191)
        ... 1 more

**Comment by webadict** [comment]
That means your cards aren't updating. Delete your metastone folder or
modify the metastone properties files to reset your cards.

**Comment by webadict** [comment]
And by metastone folder, I mean the one in your Documents folder

**Comment by demilich1** [comment]
I am wondering why this happens though. I bumped the version to 1.2.0, so all cards should be copied again even if you are running an existing 1.1.1 installation. Anyone having similar issues?

**Comment by webadict** [comment]
I'm not getting an update on my cards either. I'm looking into it now.

**Comment by webadict** [comment]
Doing a quick check of the code, it seems the updateRequired() method returns false, in spite of what it SHOULD return. Trying to figure out why.

**Comment by webadict** [comment]
Well, that's why. You're using the BuildConfig version as the local version when checking if you need an update. You need to use it as the remote version, since your local card collection is the local version.
