### ISSUE TITLE
[Bug] Battlecry crash in Sandbox Mode

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#5]
Clicking "Stop" while being prompted to select a Battlecry target in Sandbox Mode crashes the program.

**Comment by akoscz** [comment]
Here's a stacktrace of this crash
```
22:00:05 ERROR - ERROR while playing card [MINION 'Abusive Sergeant' Manacost:1] reference: [CardReference playerId:0 cardName:Abusive Sergeant cardLocation:HAND cardId:70]
22:00:05 ERROR - =========PANIC DUMP=========
java.lang.NullPointerException
	at net.demilich.metastone.game.logic.GameLogic.performGameAction(GameLogic.java:1174)
	at net.demilich.metastone.game.logic.GameLogic.resolveBattlecry(GameLogic.java:1468)
	at net.demilich.metastone.game.logic.GameLogic.summon(GameLogic.java:1615)
	at net.demilich.metastone.game.actions.PlayMinionCardAction.play(PlayMinionCardAction.java:41)
	at net.demilich.metastone.game.actions.PlayCardAction.execute(PlayCardAction.java:44)
	at net.demilich.metastone.game.logic.GameLogic.performGameAction(GameLogic.java:1183)
	at net.demilich.metastone.game.GameContext.performAction(GameContext.java:327)
	at net.demilich.metastone.game.GameContext.playTurn(GameContext.java:366)
	at net.demilich.metastone.game.GameContext.play(GameContext.java:336)
	at net.demilich.metastone.gui.sandboxmode.commands.CreateNewSandboxCommand$1.run(CreateNewSandboxCommand.java:46)
	at java.lang.Thread.run(Thread.java:745)
22:00:05 INFO  - Shutting down!
java.util.concurrent.RejectedExecutionException: Task com.sun.javafx.tk.quantum.PaintRenderJob@5bf5808d rejected from com.sun.javafx.tk.quantum.QuantumRenderer@54ca69ac[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 857]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.sun.javafx.tk.quantum.QuantumRenderer.submitRenderJob(QuantumRenderer.java:218)
	at com.sun.javafx.tk.quantum.QuantumToolkit.addRenderJob(QuantumToolkit.java:452)
	at com.sun.javafx.tk.quantum.ViewScene.repaint(ViewScene.java:140)
	at com.sun.javafx.tk.quantum.PaintCollector.renderAll(PaintCollector.java:435)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:511)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
:app:run FAILED
```
